
"""
Streamlit App: Market & Operations Insights Demo
Author: Generated by ChatGPT
Instructions:
- Place this file in the same folder as the CSVs: competitor_data.csv, operations_records.csv, weekly_kpis.csv
- Install dependencies: pip install streamlit pandas matplotlib numpy
- Run: streamlit run app.py
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from io import BytesIO

st.set_page_config(layout="wide", page_title="Market & Ops Insights Demo")

# --- Helpers ---
@st.cache_data
def load_competitor_data(path="competitor_data.csv"):
    df = pd.read_csv(path)
    # try to parse month to datetime
    try:
        df['month_dt'] = pd.to_datetime(df['month'], format="%Y-%m")
    except Exception:
        df['month_dt'] = pd.to_datetime(df['month'], errors='coerce')
    return df

@st.cache_data
def load_operations_data(path_records="operations_records.csv", path_kpi="weekly_kpis.csv"):
    df_ops = pd.read_csv(path_records, parse_dates=['date'])
    df_kpi = pd.read_csv(path_kpi)
    return df_ops, df_kpi

def fig_to_bytes(fig):
    buf = BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight")
    buf.seek(0)
    return buf

# --- Load data ---
comp_df = load_competitor_data("competitor_data.csv")
ops_df, kpi_df = load_operations_data("operations_records.csv", "weekly_kpis.csv")

# --- Sidebar controls ---
st.sidebar.header("Controls")
st.sidebar.markdown("Select filters for the visualizations below.")

# Competitor filters
competitors = comp_df['competitor'].unique().tolist()
selected_competitors = st.sidebar.multiselect("Competitors (Revenue)", competitors, default=["OurProduct","CompetitorA"])

# Month range filter (use month_dt)
min_month = comp_df['month_dt'].min()
max_month = comp_df['month_dt'].max()
start_month, end_month = st.sidebar.date_input("Month range (start, end)", value=[min_month, max_month])

# Ops filters
departments = ops_df['department'].unique().tolist()
selected_departments = st.sidebar.multiselect("Departments (Ops KPI)", departments, default=departments[:2])

# KPI week filter show N weeks
num_weeks = st.sidebar.slider("Number of weeks to show (KPIs)", min_value=4, max_value=52, value=12)

# --- Main layout ---
st.title("Market & Operations Insights — Demo")
st.markdown("Interactive demo built with Python & Streamlit. Use the sidebar to filter data and export CSVs.")

# --- Top KPIs row ---
col1, col2, col3, col4 = st.columns(4)

# Simple KPI metrics from competitor
latest_month = comp_df['month_dt'].max()
latest_data = comp_df[comp_df['month_dt']==latest_month]
our_rev = latest_data[latest_data['competitor']=="OurProduct"]['estimated_revenue'].sum() if not latest_data[latest_data['competitor']=="OurProduct"].empty else np.nan
top_comp = latest_data.loc[latest_data['estimated_revenue'].idxmax()]['competitor'] if not latest_data.empty else ""
top_comp_rev = latest_data['estimated_revenue'].max() if not latest_data.empty else np.nan

col1.metric("OurProduct Revenue (latest)", f"{int(our_rev):,}" if not pd.isna(our_rev) else "N/A")
col2.metric("Top Competitor (latest)", f"{top_comp} : {int(top_comp_rev):,}" if top_comp!="" else "N/A")
# Ops KPIs
avg_turn = kpi_df['avg_turnaround_hours'].mean() if 'avg_turnaround_hours' in kpi_df.columns else np.nan
col3.metric("Avg Turnaround (hrs)", f"{avg_turn:.1f}" if not pd.isna(avg_turn) else "N/A")
col4.metric("Data Points (ops)", f"{len(ops_df):,}")

st.markdown("---")

# --- Competitor Section ---
st.header("Competitor Analysis")
left, right = st.columns([2,1])

with left:
    st.subheader("Revenue Trend")
    # filter by month and competitor
    mask = (comp_df['month_dt'] >= pd.to_datetime(start_month)) & (comp_df['month_dt'] <= pd.to_datetime(end_month))
    df_filtered = comp_df[mask & comp_df['competitor'].isin(selected_competitors)]
    if df_filtered.empty:
        st.warning("No data for selected filters.")
    else:
        pivot = df_filtered.pivot_table(index='month_dt', columns='competitor', values='estimated_revenue', aggfunc='sum').reset_index()
        fig, ax = plt.subplots(figsize=(10,4))
        for col in pivot.columns:
            if col != 'month_dt':
                ax.plot(pivot['month_dt'], pivot[col], marker='o', label=col)
        ax.set_xlabel("Month"); ax.set_ylabel("Estimated Revenue"); ax.set_title("Revenue Trend"); ax.legend()
        fig.autofmt_xdate()
        st.pyplot(fig)
        # download option for the filtered pivot as CSV
        csv = pivot.to_csv(index=False).encode('utf-8')
        st.download_button("Download revenue trend CSV", data=csv, file_name="revenue_trend_filtered.csv", mime="text/csv")

    st.subheader("Average Ratings & Mentions (Filtered)")
    agg = df_filtered.groupby('competitor').agg(avg_rating=('avg_review_rating','mean'), mentions=('social_mentions','sum')).reset_index()
    st.dataframe(agg.style.format({"avg_rating":"{:.2f}", "mentions":"{:.0f}"}))

with right:
    st.subheader("Compare competitors")
    cmp_select = st.selectbox("Select competitor to compare with OurProduct", [c for c in competitors if c!="OurProduct"])
    compare_df = comp_df[comp_df['competitor'].isin(["OurProduct", cmp_select]) & mask]
    if not compare_df.empty:
        cmp_pivot = compare_df.pivot_table(index='month_dt', columns='competitor', values='estimated_revenue').reset_index()
        fig2, ax2 = plt.subplots(figsize=(6,3))
        for col in cmp_pivot.columns:
            if col != 'month_dt':
                ax2.plot(cmp_pivot['month_dt'], cmp_pivot[col], marker='o', label=col)
        ax2.set_xlabel("Month"); ax2.set_ylabel("Estimated Revenue"); ax2.set_title(f"OurProduct vs {cmp_select}"); ax2.legend()
        fig2.autofmt_xdate()
        st.pyplot(fig2)
    else:
        st.info("No comparison data for selected range.")

st.markdown("---")

# --- Operations Section ---
st.header("Operations Performance Tracker")
a, b = st.columns([2,1])

with a:
    st.subheader("Weekly KPIs (by department)")
    # show last N weeks
    kpi_df_sorted = kpi_df.sort_values('week', ascending=False).head(num_weeks)
    if 'week' in kpi_df_sorted.columns and 'department' in kpi_df_sorted.columns:
        st.dataframe(kpi_df_sorted)
        # plot avg_turnaround for selected departments
        plot_df = kpi_df[kpi_df['department'].isin(selected_departments)].sort_values('week')
        pivot_k = plot_df.pivot_table(index='week', columns='department', values='avg_turnaround_hours').reset_index()
        fig3, ax3 = plt.subplots(figsize=(10,4))
        for col in pivot_k.columns:
            if col != 'week':
                ax3.plot(pivot_k['week'], pivot_k[col], marker='o', label=col)
        ax3.set_xlabel("Week"); ax3.set_ylabel("Avg Turnaround Hours"); ax3.set_title("Weekly Avg Turnaround by Department"); ax3.legend()
        plt.xticks(rotation=45)
        st.pyplot(fig3)
    else:
        st.info("weekly_kpis.csv does not have the expected columns (week, department, avg_turnaround_hours)")

with b:
    st.subheader("Process Time Distribution (Ops)")
    fig4, ax4 = plt.subplots(figsize=(6,3))
    ax4.hist(ops_df['process_time_hours'].dropna(), bins=30)
    ax4.set_xlabel("Process Time Hours"); ax4.set_ylabel("Frequency"); ax4.set_title("Distribution of Process Time")
    st.pyplot(fig4)
    st.markdown("**Alerts (high turnaround weeks)**")
    # Load alerts from kpi_df where avg_turnaround_hours > threshold (dynamic threshold)
    threshold = st.number_input("Turnaround threshold (hours)", min_value=1, value=60)
    alerts = kpi_df[kpi_df['avg_turnaround_hours'] > threshold][['week','department','avg_turnaround_hours']].sort_values('avg_turnaround_hours', ascending=False)
    if not alerts.empty:
        st.table(alerts)
    else:
        st.write("No alerts found for the selected threshold.")

st.markdown("---")

# --- Data export and notes ---
st.header("Data & Notes")
st.markdown("Download the raw CSVs used by this demo. You can replace these files with your cleaned exports to show real data.")
colx, coly, colz = st.columns(3)
with colx:
    csv1 = comp_df.to_csv(index=False).encode('utf-8')
    st.download_button("Download competitor_data.csv", data=csv1, file_name="competitor_data.csv", mime="text/csv")
with coly:
    csv2 = ops_df.to_csv(index=False).encode('utf-8')
    st.download_button("Download operations_records.csv", data=csv2, file_name="operations_records.csv", mime="text/csv")
with colz:
    csv3 = kpi_df.to_csv(index=False).encode('utf-8')
    st.download_button("Download weekly_kpis.csv", data=csv3, file_name="weekly_kpis.csv", mime="text/csv")

st.markdown("----")
st.markdown("**Notes & next steps:** Replace CSVs with your real exports, or adapt the loading functions to read from a database. Consider adding sentiment analysis charts or forecasting (ARIMA, Prophet) for revenue trends.")
